[workspace]
resolver = "2"

members = [
    "http",
    "engine",
    "browser",
    "url",
]

[workspace.dependencies]
anyhow = { version = "1", features = ["backtrace"] }
thiserror = "1"

[workspace.lints.clippy]
unwrap_used = "deny"
dbg_macro = "deny"
cognitive_complexity = "warn"
