on:
  workflow_call: { }

jobs:
  install-gtk:
    name: "Install GTK4"
    runs-on: ubuntu-latest
    steps:
      - name: Install GTK4
        run: sudo apt-get update && sudo apt-get install -y libgtk-4-1 libgtk-4-dev
