name: Build/lint/test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    name: "Build and test"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install GTK4
        run: sudo apt-get update && sudo apt-get install -y libgtk-4-1 && sudo apt-get install -y libgtk-4-dev
      - name: Check formatting
        run: cargo fmt --check
      - name: Build
        run: cargo build --verbose
      - name: Run clippy
        run: cargo clippy --all-targets --all-features
      - name: Run tests
        run: cargo test --verbose
