name: Build/lint/test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  check-format:
    name: "Check code formatting"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check formatting
        run: cargo fmt --check

  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install GTK4
        run: sudo apt-get update && sudo apt-get install -y libgtk-4-1 libgtk-4-dev
      - name: Build
        run: cargo build --verbose

  lint:
    name: "Run clippy"
    runs-on: ubuntu-latest
    needs: [ "build" ]
    steps:
      - uses: actions/checkout@v4
      - name: Install GTK4
        run: sudo apt-get update && sudo apt-get install -y libgtk-4-1 libgtk-4-dev
      - name: Run clippy
        run: cargo clippy --all-targets --all-features

  test:
    name: "Run tests"
    runs-on: "ubuntu-latest"
    needs: [ "build" ]
    steps:
      - uses: actions/checkout@v4
      - name: Install GTK4
        run: sudo apt-get update && sudo apt-get install -y libgtk-4-1 libgtk-4-dev
      - name: Run tests
        run: cargo test --verbose
